server:
  port: 8080   # порт приложения

spring:
  application:
    name: bank-cards
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # validate / update / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: supersecretkeysupersecretkey123456
  expiration: 3600000   # 1 час в миллисекундах

# Swagger (springdoc-openapi)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
